on: 
    push: 
        branches:
            - main

name: Release

jobs:
    release:
      name: Release - ${{ matrix.platform.target }}
      strategy:
        matrix:
          platform:
            - os: macos-14
              target: aarch64-apple-darwin
              bin: conform
              name: conform-darwin-am64.tar.gz
              command: build

      runs-on: ${{ matrix.platform.os }}
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with: 
            submodules: recursive
        - run: |
            cat include/conformance.cmake > third_party/protobuf/cmake/conformance.cmake
            gcc --version
        - name: Install Protoc
          uses: arduino/setup-protoc@v3
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
        - name: Build binary
          uses: houseabsolute/actions-rust-cross@v0
          with:
            command: ${{ matrix.platform.command }}
            target: ${{ matrix.platform.target }}
            args: "--locked --release"
            strip: true
  